feat ICKY 304 Added code for NuxtJs/Storefront UI App layout
KiboSoftware/nuxt-storefront pull request #12
Opened 2021-10-13 11:36 UTC by kibo-nehabhanushali

feat ICKY 304 Added code for NuxtJs/Storefront UI App layout @kibo-kevinwatts

2021-10-13 23:12 UTC, kibo-kevinwatts requested changes
There should be no dependencies on Vue-Storefront/core or Vue-Storefront/kibocommerce

2021-10-14 04:43 UTC, kibo-chandradeeptalaha commented on components/AppHeader.vue
> +  // setup(props, { root }) {
Remove commented code

2021-10-14 04:43 UTC, kibo-chandradeeptalaha commented on components/AppHeader.vue
> +    // const wishlistItemTotals = computed(() => {
remove commented code

2021-10-14 04:59 UTC, kibo-chandradeeptalaha commented on package.json
> +    "@vue-storefront/core": "^2.4.3",
Remove these VSF dependencies.

2021-10-14 05:00 UTC, kibo-chandradeeptalaha commented on nuxt.config.js
> +import { VSF_LOCALE_COOKIE } from "@vue-storefront/core"
Why VSF is referenced here ?

2021-10-14 05:03 UTC, kibo-chandradeeptalaha commented on components/AppHeader.vue
> +import { categoryGetters } from "@vue-storefront/kibocommerce"
why VSF is referenced ?

2021-10-14 05:04 UTC, kibo-chandradeeptalaha requested changes
Please check the provided comments and do the needful

2021-10-14 07:05 UTC, NehaBhanushali commented
> dependencies

@kibo-kevinwatts I have removed VSF dependency and commited code again in same PR , could you please take a look and let me know if anything else.

2021-10-14 07:06 UTC, kibo-nehabhanushali commented on components/AppHeader.vue
> +  // setup(props, { root }) {
done

2021-10-14 07:06 UTC, kibo-nehabhanushali commented on components/AppHeader.vue
> +    // const wishlistItemTotals = computed(() => {
done

2021-10-14 07:07 UTC, kibo-nehabhanushali commented on package.json
> +    "@vue-storefront/core": "^2.4.3",
done

2021-10-14 07:07 UTC, NehaBhanushali commented on nuxt.config.js
> +import { VSF_LOCALE_COOKIE } from "@vue-storefront/core"
done

2021-10-14 07:07 UTC, NehaBhanushali commented on components/AppHeader.vue
> +import { categoryGetters } from "@vue-storefront/kibocommerce"
done

2021-10-14 07:08 UTC, kibo-nehabhanushali commented
> Please check the provided comments and do the needful

@kibo-chandradeeptalaha I have worked on all comments and pushed changes in same PR , could you please review

2021-10-14 07:12 UTC, kibo-chandradeeptalaha approved these changes

2021-10-18 03:01 UTC, kibo-kevinwatts approved these changes

2021-10-18 03:02 UTC, merged