feat(kibo cms): add kibo-to-vue widget factory component
KiboSoftware/nuxt-storefront pull request #171
Opened 2022-01-12 15:47 UTC by kibo-kevinwatts

2022-01-12 23:42 UTC, kibo-thomasphipps approved these changes

2022-01-12 23:42 UTC, kibo-thomasphipps commented on components/cms/KiboWidgetFactory.vue
> +      dropzoneContent,
why does it need to be returned

2022-01-12 23:42 UTC, kibo-thomasphipps commented on components/cms/KiboWidgetFactory.vue
> +      dropzoneContent,
is it because it needs to be watched

2022-01-13 08:41 UTC, kibo-chandradeeptalaha commented on components/cms/KiboProductCarousel.vue
> +    const products = computed(() => result.value?.items)
we need to define computed and onMounted here. right ?

2022-01-13 17:41 UTC, kibo-thomasphipps requested changes

2022-01-13 17:41 UTC, kibo-thomasphipps commented on composables/getters/widgetGetters.ts
> +export const widgetGetters = { dropzoneToVueComponent }
can you add a registerWidgetExport function as well.  Which would allow adding keys to the widgetToVueMap to decouple registration of new widgets

2022-01-18 18:48 UTC, merged