Bug/icky 442
KiboSoftware/nuxt-storefront pull request #172
Opened 2022-01-12 16:50 UTC by kibo-chandradeeptalaha

2022-01-12 23:59 UTC, kibo-kevinwatts requested changes
Sent you comments via slack

2022-01-13 04:14 UTC, kibo-sushant commented on assets/styles/components/atoms/SfBadge.scss
> +    font-size: calc(var(--spacer-2xs) * 3);
For font, use font variables like --font-size--*

2022-01-13 04:14 UTC, kibo-sushant commented on pages/product/index.vue
> +      // selectFulfillmentOption,
remove it, if not getting used

2022-01-13 08:08 UTC, closed without merging

2022-01-13 08:09 UTC, kibo-chandradeeptalaha commented
Opening a new PR with only the ticket changes.