feat: cart responsiveness
KiboSoftware/nuxt-storefront pull request #320
Opened 2022-04-15 05:51 UTC by kibo-chandradeeptalaha

2022-04-18 22:02 UTC, kibo-kevinwatts requested changes

2022-04-18 22:02 UTC, kibo-kevinwatts commented on components/KiboCollectedProduct.vue
> +        showMobileCartActions.value = !showMobileCartActions.value
For any / all window "click" events, we're toggling the state?

2022-04-19 13:34 UTC, kibo-chandradeeptalaha commented on components/KiboCollectedProduct.vue
> +        showMobileCartActions.value = !showMobileCartActions.value
Modified: Toggling the state if the menu is open at the time of click event.

2022-04-20 20:39 UTC, kibo-kevinwatts approved these changes

2022-04-20 20:39 UTC, merged