feat(Return Items): return order items
KiboSoftware/nuxt-storefront pull request #356
Opened 2022-07-07 15:40 UTC by amolpawar-kibo

2022-07-08 06:35 UTC, sss-bct requested changes

2022-07-08 06:35 UTC, kibo-susantasamanta commented on composables/useReturnItems.ts
> +        // notes,
Remove commented if not required, Is it used anywhere?

2022-07-08 06:35 UTC, kibo-susantasamanta commented on composables/index.ts
> +export * from "./useReturnReasons"
Only for loading reasons we are using this composable. Can we not include this inside useReturnItems hook ?

2022-07-08 07:24 UTC, amolpawar-kibo commented on composables/useReturnItems.ts
> +        // notes,
Resolved

2022-07-11 07:09 UTC, amolpawar-kibo commented on composables/index.ts
> +export * from "./useReturnReasons"
I think It's  better to keep separate composable.

2022-07-11 17:27 UTC, kibo-kevinwatts requested changes

2022-07-11 17:27 UTC, kibo-kevinwatts commented on components/KiboOrderItemDetails.vue
> +              {{ "Choose a response" }}
Should this be an option?

2022-07-11 17:27 UTC, kibo-kevinwatts commented on composables/index.ts
> +export * from "./useReturnReasons"
I think its better to keep them separate, for populating the return reasons drop down

2022-07-11 17:27 UTC, kibo-kevinwatts commented on components/KiboOrderItemDetails.vue
> +        originalOrderId: props.order.id,
nitpick, use the computed property, "orderId" instead of using "props.order"

2022-07-11 17:27 UTC, kibo-kevinwatts commented on components/KiboOrderItemDetails.vue
>          </div>
Should we Make the Order Returns a separate component? After shopper clicks "Return Items" use a different component instead of this existing Order Details one. This component is now pretty large in size

2022-07-12 12:00 UTC, amolpawar-kibo commented on components/KiboOrderItemDetails.vue
>          </div>
Resolved.

2022-07-12 12:01 UTC, amolpawar-kibo commented on components/KiboOrderItemDetails.vue
> +        originalOrderId: props.order.id,
Resolved.

2022-07-12 12:01 UTC, amolpawar-kibo commented on components/KiboOrderItemDetails.vue
> +              {{ "Choose a response" }}
Resolved.

2022-07-15 19:00 UTC, kibo-kevinwatts approved these changes

2022-07-19 04:32 UTC, sss-bct approved these changes

2022-07-19 04:55 UTC, merged